export const icons = {
  WPawnIcon: '<i class="fa-sharp fa-regular fa-chess-pawn"></i>',
  BPawnIcon: '<i class="fa-solid fa-chess-pawn"></i>',
  WPawnIcon: '<i class="fa-sharp fa-regular fa-chess-pawn"></i>',
  BRookIcon: '<i class="fa-solid fa-chess-rook"></i>',
  WRookIcon: '<i class="fa-regular fa-chess-rook"></i>',
  BKnightIcon: '<i class="fa-solid fa-chess-knight"></i>',
  WKnightIcon: '<i class="fa-regular fa-chess-knight"></i>',
  BBishopIcon: '<i class="fa-solid fa-chess-bishop"></i>',
  WBishopIcon: '<i class="fa-regular fa-chess-bishop"></i>',
  BQueenIcon: '<i class="fa-solid fa-chess-queen"></i>',
  WQueenIcon: '<i class="fa-regular fa-chess-queen"></i>',
  BKingIcon: '<i class="fa-solid fa-chess-king"></i>',
  WKingIcon: '<i class="fa-regular fa-chess-king"></i>',
}
