export const startingFigures = [
  { coordinate: 'A2', figure: 'WPawn' },
  { coordinate: 'B2', figure: 'WPawn' },
  { coordinate: 'C2', figure: 'WPawn' },
  { coordinate: 'D2', figure: 'WPawn' },
  { coordinate: 'E2', figure: 'WPawn' },
  { coordinate: 'F2', figure: 'WPawn' },
  { coordinate: 'G2', figure: 'WPawn' },
  { coordinate: 'H2', figure: 'WPawn' },
  { coordinate: 'A7', figure: 'BPawn' },
  { coordinate: 'B7', figure: 'BPawn' },
  { coordinate: 'C7', figure: 'BPawn' },
  { coordinate: 'D7', figure: 'BPawn' },
  { coordinate: 'E7', figure: 'BPawn' },
  { coordinate: 'F7', figure: 'BPawn' },
  { coordinate: 'G7', figure: 'BPawn' },
  { coordinate: 'H7', figure: 'BPawn' },

  { coordinate: 'A1', figure: 'WRook' },
  { coordinate: 'H1', figure: 'WRook' },
  { coordinate: 'B1', figure: 'WKnight' },
  { coordinate: 'G1', figure: 'WKnight' },
  { coordinate: 'C1', figure: 'WBishop' },
  { coordinate: 'F1', figure: 'WBishop' },
  { coordinate: 'D1', figure: 'WQueen' },
  { coordinate: 'E1', figure: 'WKing' },

  { coordinate: 'A8', figure: 'BRook' },
  { coordinate: 'H8', figure: 'BRook' },
  { coordinate: 'B8', figure: 'BKnight' },
  { coordinate: 'G8', figure: 'BKnight' },
  { coordinate: 'C8', figure: 'BBishop' },
  { coordinate: 'F8', figure: 'BBishop' },
  { coordinate: 'D8', figure: 'BQueen' },
  { coordinate: 'E8', figure: 'BKing' },
]
